spring.application.name=compendium-service
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/dnd_compendium_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tu_contraseña

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true