# 1. Identificación del Microservicio
spring.application.name=rng-service

# El puerto 8088 es CRUCIAL porque es donde el character-service va a ir a buscar los dados
server.port=8096

# 2. Conexión a tu XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/dnd_rng_db?createDatabaseIfNotExist=true
spring.datasource.username=root

# Recuerda: ¡Ni un solo espacio después del signo igual!
spring.datasource.password=

# 3. Comportamiento de Base de Datos
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false