# 1. Identificación del Microservicio
spring.application.name=character-service
server.port=8081

# 2. Conexión a tu XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/dnd_character_db?createDatabaseIfNotExist=true
spring.datasource.username=root

# ¡Ojo aquí! Asegúrate de que no quede ni un solo espacio en blanco después del igual
spring.datasource.password=

# 3. Comportamiento de Base de Datos
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false