spring.application.name=asset-service
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/dnd_asset_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tu_contraseña

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true